#! /usr/bin/perl
use strict;

open FOER, "<foer.bin" or die "could not open foer.bin\n";
my $foer = join('', <FOER>);
close FOER;
open FOERASM, "<foerbin.asm" or die "could not open foerbin.asm\n";
my $needed = 0;
while (<FOERASM>) {
  /\srb\s([^;]+)/ && ($needed += eval $1);
}

print <<EOC;
| -------------------------------------------------------------------
| FOeRTHchen
| Autor: Helmar Wodtke 2005
| -------------------------------------------------------------------
|
| THIS IS AUTOGENERATED SOURCE! DO NOT CHANGE!
|
: hexd dup 1+ swap c\@ 32 or '0 - dup 9 >if 39 - then  ;
: hexb hexd 4 << >r hexd r> or 1, ;
: hex: 32 parse 1 >>       [ here ]
  dup 0 <>if 1- >r hexb r> [ swap compile ] ;; then drop ;
create foercode
EOC

for (my $i = 0; $i < length($foer); $i += 32) {
  print "hex: ", unpack("H*", substr($foer, $i, 32)), "\n";
}
print <<EOC
$needed allot
decimal
: foerCCT foercode dup 2 + @ + ;
' emit foerCCT -6 cells + !
' key  foerCCT -7 cells + !
: foerthchen foercode execute ." <--foerthchen done." cr ;
EOC
